
package ejercicio1;

import ejercicio1.AgregarCalificaciones;
import javax.swing.table.DefaultTableModel;
import ejercicio1.datos.KardexDatos;
import ejercicio1.datos.Materias;
import javax.swing.JOptionPane;


/**
 *
 * @author rafae
 */
public class TablaKardex extends javax.swing.JFrame {
        DefaultTableModel modelo;

    /**
     * Creates new form TablaKardex
     */
    public TablaKardex() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
        // aqui porque no me estaba dejando editar directo en la tabla por queeeeeee!!!!!!!!!!!!!!!!!
        jTableMaterias.setDefaultEditor(Object.class, null);

    }
    
    
    private void actualizarPromedio() {
        int filas = jTableMaterias.getRowCount();
            if (filas == 0) {
                labelPromedio.setText("0.0");
                return;
                }

        double suma = 0;
        int cantidad = 0;

            for (int i = 0; i < filas; i++) {
                Object valor = jTableMaterias.getValueAt(i, 2); // columna 1 = calificación
            if (valor != null && !valor.toString().isEmpty()) {
              try {
                suma += Double.parseDouble(valor.toString());
                cantidad++;
            } catch (NumberFormatException e) {
                
            }
        }
    }

    if (cantidad > 0) {
        double promedio = suma / cantidad;
        labelPromedio.setText(String.format("%.2f", promedio)); // muestra con 2 decimales
    } else {
        labelPromedio.setText("0.0");
    }
    }


    
    
    private void cargarTabla() {
      modelo = new DefaultTableModel(
        new Object[]{"Materia", "Semestre", "Calificación",}, 0
          ) {
        //no quiero editar sobre la tabla, lo edita desde auqi
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

        jTableMaterias.setModel(modelo);
       modelo.setRowCount(0);

       double suma = 0;
       int contador = 0;

       for (Materias m : KardexDatos.listaMaterias) {
        double promedio = m.getPromedio();
        modelo.addRow(new Object[]{
            m.getNombre(),
            m.getSemestre(),
            m.getCalificaciones(),
            promedio
        });

        suma += promedio;
        contador++;
    }

    // calcula el promedio conforme agrego calificaciones directo al label 
    double promedioGeneral = (contador > 0) ? (suma / contador) : 0.0;
    labelPromedio.setText(String.format("%.2f", promedioGeneral));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        labelPromedio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterias);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        labelPromedio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPromedio.setText("0.0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tabla de calificaciones: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Promedio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPromedio)
                        .addGap(70, 70, 70)
                        .addComponent(btnAgregar)
                        .addGap(49, 49, 49)
                        .addComponent(btnModificar)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel3)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPromedio)
                        .addGap(30, 30, 30)))
                .addComponent(btnEliminar)
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(317, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(102, 102, 102)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //boton para agregar
        AgregarCalificaciones dialog = new AgregarCalificaciones(this, true);
        dialog.setVisible(true);
        cargarTabla();
        actualizarPromedio();
        JOptionPane.showMessageDialog(this, "Materia agregada correctamente.");
     
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // boton para eliominar de la tabla
        int fila = jTableMaterias.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona una materia para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
                }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar esta materia?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                KardexDatos.listaMaterias.remove(fila);
                cargarTabla();
                actualizarPromedio();
                JOptionPane.showMessageDialog(this, "Materia eliminada correctamente.");
                }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //boton para modificar materias 
           int fila = jTableMaterias.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona una materia para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
                     }
                Materias materiaSeleccionada = KardexDatos.listaMaterias.get(fila);
                AgregarCalificaciones dialog = new AgregarCalificaciones(this, true, materiaSeleccionada);
                dialog.setVisible(true);
                cargarTabla();
                actualizarPromedio();
                JOptionPane.showMessageDialog(this, "Materia modificada correctamente.");
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaKardex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel labelPromedio;
    // End of variables declaration//GEN-END:variables
}
